(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Running Strong Coupling: 


BeginPackage["Coupling`"]
alpha::usage =
	"alpha[\!\(\*SuperscriptBox[\(\[Mu]\), \(2\)]\)] is the PDG four loop running coupling with flavor transitions.";


Needs["ErrorBarPlots`"]
Needs["ErrorBarLogPlots`"]


Begin["Private`"]


Loggers[musq_,lamsq_] := Log[musq/lamsq] (** Shorthand for Log (Q^2/\Lambda^2). **)


beta0[nf_] := (33 - 2 nf)/12 / Pi
beta1[nf_] := (153 - 19 nf)/24 / Pi^2 
beta2[nf_] := (77139 - 15099 nf + 325 nf^2) / 3456 / Pi^3
beta3[nf_] := -(29243 - 6946.3 nf + 405.089 nf^2 + 1.49931 nf^3) / 256 / Pi^4


Lambda3 = .339;
Lambda4 = .296;
Lambda5 = .213;


mcharm = 1.275;
mbottom = 4.180;
mZ = 91.188;


c11 = 1 / 6 / Pi ;
c10 = 0;
c20 = -11 / 71 / Pi /Pi ;
c21 = 19/24 /Pi /Pi ;
c22 = c11^2;


coeffs = {{c10,c11},{c20,c21,c22}};


al4[musq_,nf_,lamsq_] := 1 / beta0[nf] /Loggers[musq,lamsq] - (1 / beta0[nf]^3 / Loggers[musq,lamsq]^2)beta1[nf] Log[Loggers[musq,lamsq]] +
(1 / beta0[nf]^3 / Loggers[musq,lamsq]^3)((beta1[nf]^2 / beta0[nf]^2) (Log[Loggers[musq,lamsq]]^2 - Log[Loggers[musq,lamsq]] - 1) + (beta2[nf]/beta0[nf]))+(1/beta0[nf]^4 / Loggers[musq,lamsq]^4) ((beta1[nf]^3/beta0[nf]^3)(-Log[Loggers[musq,lamsq]]^3 + (5/2)Log[Loggers[musq,lamsq]]^2 + 2 Log[Loggers[musq,lamsq]] - 1/2)) - (1/beta0[nf]^4/Loggers[musq,lamsq]^4)((3 beta1[nf] beta2[nf]/beta0[nf]^2)Log[Loggers[musq,lamsq]] + beta3[nf]/2 / beta0[nf])


al3[musq_,nf_,lamsq_] := 1 / beta0[nf] /Loggers[musq,lamsq] - (1 / beta0[nf]^3 / Loggers[musq,lamsq]^2)beta1[nf] Log[Loggers[musq,lamsq]] +
(1 / beta0[nf]^3 / Loggers[musq,lamsq]^3)((beta1[nf]^2 / beta0[nf]^2) (Log[Loggers[musq,lamsq]]^2 - Log[Loggers[musq,lamsq]] - 1) + (beta2[nf]/beta0[nf]))


al2[musq_,nf_,lamsq_] := 1 / beta0[nf] /Loggers[musq,lamsq] - (1 / beta0[nf]^3 / Loggers[musq,lamsq]^2)beta1[nf] Log[Loggers[musq,lamsq]] 
     


al3to4[musq_] := If[al4[musq,4,Lambda4^2]< al4[musq,3,Lambda3^2],al4[musq,3,Lambda3^2],al4[musq,4,Lambda4^2]]



al4to5[musq_] := If[al4[musq,5,Lambda5^2]< al3to4[musq],al3to4[musq],al4[musq,5,Lambda5^2]]


alpha[musq_] := al4to5[musq]


End[];
EndPackage[];
